__title__ = "nosorog"
__description__ = "An assertive security library."
__url__ = "https://nosorog.readthedocs.io"
__version__ = "0.2.0"
__author__ = "Vyacheslav Lobanov"
__author_email__ = "bartoldo@bk.ru"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2022 Vyacheslav Lobanov"
